### ISSUE TITLE
Problem installing via pip

### ISSUE THREAD

**Issue by beachbumbob** [codenio/Mock.GPIO#1]
Clean Debian 10 without gui.
Only installed sudo, aptitude, python-pip and python3-pip after installing OS
reboot

pip install Mock.GPIO
Collecting Mock.GPIO
  Using cached https://files.pythonhosted.org/packages/57/cf/c8fcd87526a42885c96230f727063d011ac68963dc28e5e80004d9d950fa/Mock.GPIO-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RYHKy6/Mock.GPIO/setup.py", line 54, in <module>
        with open('requirements.txt', 'r') as requirements_file:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-RYHKy6/Mock.GPIO/

**Comment by codenio** [comment]
@beachbumbob, this issue is resolved now.
Try installing the latest version using the following commands
```
$ pip3 install Mock.GPIO
or 
$ pip3 install Mock.GPIO==0.1.7
```
let me know in case if this issues exist.

**Comment by beachbumbob** [comment]
The solution for "pip install Mock.GPIO" and  "pip3 install Mock.GPIO" worked. "pip3 install Mock.GPIO==0.1.7" returned, as expected, "Requirement already satisfied".

As far as I can se the issue is solved.

**Comment by codenio** [comment]
Thanks, @beachbumbob for the confirmation :+1:
