### ISSUE TITLE
Fix import in readme 

### ISSUE THREAD

**Issue by onskateboard** [codenio/Mock.GPIO#3]
import Mock.GPIO as GPIO (like in the example)

**Comment by codenio** [comment]
@onskateboard thanks for creating the issue, can you be specific..?

**Comment by onskateboard** [comment]
in your docu you suggest after installing:
To use the emulator just type the following at the beginning of your script. 

`from Mock.GPIO import GPIO`

but you can import only: `from Mock Import GPIO` 
or you can import it like in your examples ` import Mock.GPIO as GPIO`

**Comment by codenio** [comment]
Thanks @onskateboard, resolved this issue now. 

looking forward to seeing more suggestions.
