### ISSUE TITLE
GPIO.py has an unused import — yaml

### ISSUE THREAD

**Issue by electronhead** [codenio/Mock.GPIO#4]
The unused import of yaml in GPIO.py hasn’t been an issue until I tried to use the library using the iOS Juno app. 
```
"""
Mock Library for RPi.GPIO
"""

import time
import logging
import os
import yaml

logger = logging.getLogger(__name__)
...
...
```
setup.py shows an install dependency on PyYAML==5.3.1.

I might not be understanding the code, and I’m new to pypi and Python packaging.

Otherwise, the library has been very useful for developing on non-raspberry pi’s and then deploying to the pi’s. Saved a lot of effort.

Any thoughts beyond my downloading and making the change locally.

**Comment by codenio** [comment]
@electronhead thanks for reaching out. I have removed the unused dependency.

**Comment by electronhead** [comment]
Thank-you. My library now runs on iOS using Juno.
