### ISSUE TITLE
Support multiple channels in the setup function

### ISSUE THREAD

**Issue by gvigh** [codenio/Mock.GPIO#7]
Currently the Mock implementation of `setup` only allows one channel as it's first parameter.

According to the [RPi.GPIO documentation](https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/), (and my own testing) the RPi.GPIO `setup` function supports the initialization of multiple channels with only one call:

```python
chan_list = [11,12]    # add as many channels as you want!
                       # you can tuples instead i.e.:
                       #   chan_list = (11,12)
GPIO.setup(chan_list, GPIO.OUT)
```
*taken from the 'Setup more than one channel' section in the linked docs*

This should also work when providing an initial value:

```python
GPIO.setup([11, 12], GPIO.OUT, initial=GPIO.LOW)
```

Since one of the goals of this project is to make the switching between the two modules seamless, I would recommend fixing this small difference :)

**Comment by codenio** [comment]
Thanks @gvigh for creating this issue.

I have made necessary changes to support channels list or channels tuple in GPIO.setup(), GPIO.output() and GPIO.cleanup() as per the documentation provided [RPI.GPIO Documentation]( https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/)

do let me know if further improvements are required.
